### ISSUE TITLE
This project alive?

### ISSUE THREAD

**Issue by jconti** [ReactiveX/RxClojure#172]
RxJava 1.2 is out.  Is anyone home here, or is this the end?

**Comment by akarnokd** [comment]
I don't think so and I don't know Clojure at all.

**Comment by daveray** [comment]
I don't really use rx anymore or have time to maintain this. If someone wanted to keep things up-to-date, that would be great. Otherwise, I guess it languishes. :(

**Comment by jconti** [comment]
Thank you for the replies.  I will see what I can do.

**Comment by niwinz** [comment]
There are an alternative package that already works with rxjava2: https://github.com/funcool/beicon

**Comment by jconti** [comment]
I have had good results with https://github.com/funcool/beicon.

**Comment by dchacke** [comment]
I would also imagine there is some significant overlap between this lib and core.async.

**Comment by jconti** [comment]
I think core.async is lower level, but lighter and more flexible. I think the natural successor to this project is https://github.com/funcool/beicon. It is a clean simple design and the team is active.

**Comment by avelino** [comment]
It's a shame the project has stopped, but it is possible to use the `RxJava` JVM is beautiful

**Comment by jconti** [comment]
https://github.com/funcool/beicon is a good design for the same purpose.

**Comment by avelino** [comment]
@jconti I saw that your fork[1] is more up to date than the officer, wouldn't you like to keep it here?

[1] https://github.com/jconti/rxclojure
