### ISSUE TITLE
Gradle-specific "plus" version dep causes intermittent build errors in Leiningen

### ISSUE THREAD

**Issue by timmc** [ReactiveX/RxClojure#2]
build.gradle contains `org.clojure:clojure:1.4.+` and so does the resulting pom.xml, which occasionally causes Leiningen to attempt to download that non-existent version. I don't think anything except Gradle understands pluses in version strings; perhaps you can just release with the minimum supported Clojure version specified? I think Maven will automatically pick the higher version in case of a conflict.

**Comment by daveray** [comment]
Hey. I'm happy to make that change as soon as the build for the new non-monolithic rx projects is ironed out. At the moment, I don't actually know how to build RxClojure :)

**Comment by timmc** [comment]
Further info: It turns out I can't even use exclusions to fully fix this problem. If I have a library that depends on rxjava-clojure and excludes the clojure dependency, and then an application that depends on my library, the application _also_ needs an exclusion for the transitive clojure dependency. In other words, the broken version number leaks out to all transitive dependants.

For now, the workaround is to put exclusions in each downstream project.clj or pom.xml.

**Comment by daveray** [comment]
Hi. This will be fixed once https://github.com/ReactiveX/RxClojure/pull/3 is merged and a new release is pushed. Sorry about the slow response. You caught the project in a transition :)

**Comment by timmc** [comment]
No worries! We're just slapping :excludes on everything for now, and that's mostly working.

**Comment by daveray** [comment]
A release candidate with a fix is in maven central now: `[io.reactivex/rxclojure "1.0.0-rc.1"]`
